/*
 * ViewComment.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import model.Business;
import model.Food;
import server.Client;

/**
 *
 * @author  __USER__
 */
public class CommentView extends javax.swing.JFrame implements MouseListener {

	Business business = new Business();

	/** Creates new form ViewComment */
	public CommentView() {
		initComponents();

		/*处理页面美化*/
		this.drawViewComment();

		this.setResizable(false);
		this.setLocationRelativeTo(null);
		
		this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	}

	public CommentView(Business business) {
		this.business = business;

		initComponents();

		/*处理页面美化*/
		this.drawViewComment();

		/*显示该商店所有商品*/
		try {
			this.showFood(business);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();

		}

		this.setResizable(false);
		this.setLocationRelativeTo(null);
		
		this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jScrollPane1
				.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

		jPanel2.setPreferredSize(new java.awt.Dimension(100, 10000));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 755,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 10000,
				Short.MAX_VALUE));

		jScrollPane1.setViewportView(jPanel2);

		jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel1.setText("\u8bc4\u4ef7");

		jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel2MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774,
				Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel1Layout.createSequentialGroup().addContainerGap(362,
						Short.MAX_VALUE).addComponent(jLabel1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 112,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(229,
						229, 229).addComponent(jLabel2,
						javax.swing.GroupLayout.PREFERRED_SIZE, 44,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(27, 27,
						27)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel1)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																43,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												488, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		try {
			org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
		} catch (Exception e) {
			//TODO exception
		}

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CommentView().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;

	// End of variables declaration//GEN-END:variables

	/**
	 * 处理页面美化
	 */

	public void drawViewComment() {
		jPanel1.setBackground(new Color(95, 142, 230));
		jLabel1.setForeground(Color.WHITE);
		
		ImageIcon icon = new ImageIcon("Image/flash.png");
		Image img = icon.getImage().getScaledInstance(jLabel2.getWidth(),
				jLabel2.getHeight(), Image.SCALE_DEFAULT);

		icon = new ImageIcon(img);
		this.jLabel2.setIcon(icon);
	}

	/**管理食物**/
	ArrayList<Food> foods;
	ArrayList<JPanel> jPanels;
	ArrayList<JLabel> imageLabels;
	ArrayList<JLabel> nameLabels;
	ArrayList<JLabel> describeLabels;
	ArrayList<JLabel> sellCountLabels;
	ArrayList<JLabel> priceLabels;
	Color color;

	public void showFood(Business business) throws UnknownHostException,
			IOException, ClassNotFoundException, SQLException {

		Client client = new Client();
		foods = client.showFood(business.getBid());

		jPanels = new ArrayList<JPanel>();
		imageLabels = new ArrayList<JLabel>();
		nameLabels = new ArrayList<JLabel>();
		describeLabels = new ArrayList<JLabel>();
		sellCountLabels = new ArrayList<JLabel>();
		priceLabels = new ArrayList<JLabel>();

		System.out.println("B" + foods.size());

		for (int i = 0; i < foods.size(); i++) {

			/*首先放一个面板进去*/
			jPanels.add(new JPanel());
			jPanels.get(i).setSize(jPanel2.getWidth(), 120);
			jPanels.get(i).setBounds(0, jPanels.get(i).getHeight() * i,
					jPanel2.getWidth(), 120);
			jPanels.get(i).setBorder(BorderFactory.createEtchedBorder());
			jPanel2.add(jPanels.get(i));

			/*设置jPanel面板最大值*/
			Dimension ds = new Dimension(jPanel2.getWidth(), jPanels.get(i)
					.getHeight()
					* i + 150);
			jPanel2.setPreferredSize(ds);

			//获取背景颜色
			color = jPanels.get(i).getBackground();

			/*添加食物图像*/

			ImageIcon icon = new ImageIcon("Image/Food/"
					+ foods.get(i).getImage());
			imageLabels.add(new JLabel());
			jPanels.get(i).setLayout(null);
			imageLabels.get(i).setBounds(10, 10, 100, 100);

			Image temp = icon.getImage().getScaledInstance(
					imageLabels.get(i).getWidth(),
					imageLabels.get(i).getHeight(), Image.SCALE_DEFAULT);
			icon = new ImageIcon(temp);

			imageLabels.get(i).setIcon(icon);
			jPanels.get(i).add(imageLabels.get(i));

			/*添加食物名字*/
			nameLabels.add(new JLabel(foods.get(i).getFoodName()));
			nameLabels.get(i).setBounds(120, 5, 140, 50);
			nameLabels.get(i).setFont(new java.awt.Font("微软雅黑", 0, 18));
			jPanels.get(i).add(nameLabels.get(i));

			/*添加月售多少份*/
			sellCountLabels.add(new JLabel("月售:" + foods.get(i).getSellcount()
					+ "" + "份"));
			sellCountLabels.get(i).setBounds(120, 40, 140, 50);
			jPanels.get(i).add(sellCountLabels.get(i));

			/*添加描述*/
			describeLabels.add(new JLabel("描述:"
					+ foods.get(i).getFoodInformation()));
			describeLabels.get(i).setBounds(120, 70, 180, 50);
			jPanels.get(i).add(describeLabels.get(i));

			/*添加价格*/
			priceLabels.add(new JLabel("￥" + foods.get(i).getFoodPrice()));
			priceLabels.get(i).setBounds(620, 70, 50, 50);
			jPanels.get(i).add(priceLabels.get(i));

			jPanels.get(i).addMouseListener(this);
		}
	}

	/**
	 * 点击查看评论
	 * @param e
	 */
	@Override
	public void mouseClicked(MouseEvent e) {
		// TODO Auto-generated method stub
		for (int i = 0; i < foods.size(); i++) {
			if (e.getSource().equals(jPanels.get(i))) {
				System.out.println("菜品：" + i);
				new FoodCommentView(business, i).setVisible(true);
			}
		}
	}

	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub
		for (int i = 0; i < foods.size(); i++) {
			if (e.getSource().equals(jPanels.get(i)))
				jPanels.get(i).setBackground(new Color(173, 175, 173, 80));
		}

	}

	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub
		for (int i = 0; i < foods.size(); i++) {
			if (e.getSource().equals(jPanels.get(i)))
				jPanels.get(i).setBackground(color);
		}
	}

	@Override
	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub

	}
	
	/**
	 * 刷新
	 */
	
	private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		
		try {
			jPanel2.removeAll();
			showFood(business);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	

}