/*
 * HomeView.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.print.attribute.AttributeSetUtilities;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.border.TitledBorder;

import server.Client;

import model.Business;
import model.Courier;
import model.Customer;
import model.ModelFactory;
import model.Shop;

/**
 *
 * @author  __USER__
 */
public class HomeView extends javax.swing.JFrame implements MouseListener {

	//传参，方便判断身份
	Customer customer = new Customer();
	Business business = new Business();
	Courier courier = new Courier();

	
	/**
	 * 判断用户是否登陆
	 */
	boolean isLogin = false;
	
	public void isLogined(boolean isLogin) {
		isLogin = this.isLogin;
		
		if(!isLogin) {
			new LoginView().setVisible(true);
			this.dispose();
		}
	}
	
	
	/** Creates new form HomeView */
	public HomeView() {
		initComponents();
		setsearch();
		jLabel1.setText("地址...");

		this.jMenu1.remove(jMenuItem3); //登陆前删除无关菜单项
		this.jMenu1.remove(jMenuItem4);
		this.jMenu1.remove(jMenuItem5);
		this.jMenu1.remove(jMenuItem6);

		//处理主页美化
		try {
			this.drawHome();
		} catch (Exception e1) {
			// TODO Auto-generated catch block

			e1.printStackTrace();
		}

		/*显示所有商家*/
		try {
			this.getAllBusiness();
		} catch (Exception e) {
			// TODO Auto-generated catch block

			e.printStackTrace();
		}

		jScrollPane1
				.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

		this.setResizable(false);
		this.setLocationRelativeTo(null);
		
	
	}

	/**传参，显示登陆后身份
	 * 
	 * @param customer
	 */

	public HomeView(Customer customer) {

		this.customer = customer;
		initComponents();

		this.jMenu1.setText(customer.getCname());
		this.jMenu1.remove(jMenuItem1); //登陆后删除登陆项
		this.jMenu1.remove(jMenuItem2); //登陆后删除注册项
		
		jLabel1.setText("" + customer.getAddress());

		jScrollPane1
				.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
		
		
		/*已登录*/
		isLogin = true;

		//处理主页美化
		try {
			this.drawHome();
			this.getAllBusiness();
		} catch (Exception e1) {
			// TODO Auto-generated catch block

			e1.printStackTrace();
		}

		this.setResizable(false);
		this.setLocationRelativeTo(null);
		
	
	}

	public HomeView(Business business) throws UnknownHostException, IOException, ClassNotFoundException {
		this.business = business;
		initComponents();
		
		this.jMenu1.setText(business.getBname());

		this.jMenu1.remove(jMenuItem1); //登陆后删除登陆项

		jScrollPane1
				.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
		
		new Market(business).setVisible(true);
		this.dispose();
		
	}

	public HomeView(Courier courier) {
		this.courier = courier;
		initComponents();
		this.jMenu1.setText(courier.getConame());
		this.jMenu1.remove(jMenuItem1); //登陆后删除登陆项

		jScrollPane1
				.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
		this.playTest();
		this.setResizable(false);
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel2 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		jRadioButton4 = new javax.swing.JRadioButton();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel8 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenuItem6 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
		jScrollPane1
				.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

		jPanel2.setMinimumSize(new java.awt.Dimension(100, 10000));

		jLabel9.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel9.setText("\u7f8e\u98df");

		jLabel10.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel10.setText("\u5348\u9910");

		jLabel2.setText("1");
		jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel2MouseClicked(evt);
			}
		});

		jLabel3.setText("2");
		jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel3MouseClicked(evt);
			}
		});

		jLabel4.setText("3");
		jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel4MouseClicked(evt);
			}
		});

		jLabel6.setText("5");
		jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel6MouseClicked(evt);
			}
		});

		jLabel5.setText("4");
		jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel5MouseClicked(evt);
			}
		});

		jLabel11.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel11.setText("\u5feb\u9910");

		jLabel12.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel12.setText("\u996e\u54c1");

		jLabel13.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel13.setText("\u66f4\u591a");

		jLabel7.setBackground(new java.awt.Color(255, 255, 255));
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));

		jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
		buttonGroup1.add(jRadioButton1);
		jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton1ActionPerformed(evt);
			}

			private void jRadioButton1ActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				
			}
		});

		jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
		buttonGroup1.add(jRadioButton2);
		jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton2ActionPerformed(evt);
			}

			private void jRadioButton2ActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				
			}
		});

		jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
		buttonGroup1.add(jRadioButton3);

		jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
		buttonGroup1.add(jRadioButton4);
		jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton4ActionPerformed(evt);
			}

			private void jRadioButton4ActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap(108, Short.MAX_VALUE)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				69,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				71,
																				71,
																				71))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel9)
																		.addGap(
																				90,
																				90,
																				90)))
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				69,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				60,
																				60,
																				60)
																		.addComponent(
																				jLabel4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				69,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				66,
																				66,
																				66)
																		.addComponent(
																				jLabel5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				69,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				77,
																				77,
																				77))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel10)
																		.addGap(
																				101,
																				101,
																				101)
																		.addComponent(
																				jLabel11)
																		.addGap(
																				113,
																				113,
																				113)
																		.addComponent(
																				jLabel12)
																		.addGap(
																				94,
																				94,
																				94)))
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(
																				27,
																				27,
																				27)
																		.addComponent(
																				jLabel6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				69,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(
																				50,
																				50,
																				50)
																		.addComponent(
																				jLabel13)))
										.addGap(135, 135, 135))
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(381, 381, 381)
										.addComponent(jRadioButton1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jRadioButton2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jRadioButton3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jRadioButton4)
										.addContainerGap(405, Short.MAX_VALUE))
						.addComponent(jLabel7,
								javax.swing.GroupLayout.DEFAULT_SIZE, 889,
								Short.MAX_VALUE));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addComponent(
												jLabel7,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												174,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jRadioButton2,
																0, 0,
																Short.MAX_VALUE)
														.addComponent(
																jRadioButton1,
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jRadioButton3,
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jRadioButton4,
																javax.swing.GroupLayout.Alignment.LEADING))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																64,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																64,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																64,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																64,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																64,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(1, 1, 1)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel13,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																22,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel4Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jLabel12)
																		.addComponent(
																				jLabel11)
																		.addComponent(
																				jLabel9,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				27,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel10)))
										.addGap(19, 19, 19)));

		jPanel3.setBackground(new java.awt.Color(51, 102, 255));

		jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("\u4e2d\u5927\u5357\u65b9B2\u5730\u4e0b\u9053");
		jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel1MouseClicked(evt);
			}
		});

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}

			private void jTextField1ActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				
			}
		});

		jButton1.setText("\u641c\u7d22");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton1ActionPerformed(evt);
				} catch (UnknownHostException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8.setText("\u4eca\u65e5\u7279\u60e0");

		jLabel15.setText("jLabel15");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				223,
																				223,
																				223)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				410,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				50,
																				50,
																				50)
																		.addComponent(
																				jButton1))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												177,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												95,
																												95,
																												95)
																										.addComponent(
																												jLabel15,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												465,
																												Short.MAX_VALUE))
																						.addComponent(
																								jLabel8,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								258,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(137, Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				37,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jLabel15,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addGap(28, 28, 28)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton1))
										.addGap(240, 240, 240)
										.addComponent(
												jLabel8,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jLabel14.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel14
				.setText("\u2014\u2014   \u63a8\u8350\u5546\u5bb6   \u2014\u2014");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																jPanel3,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				342,
																				342,
																				342)
																		.addComponent(
																				jLabel14))
														.addComponent(
																jPanel4,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap(221, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												138,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(26, 26, 26)
										.addComponent(
												jLabel14,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												24,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(204, Short.MAX_VALUE)));

		jScrollPane1.setViewportView(jPanel2);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
		jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

		jMenu1.setBackground(new java.awt.Color(255, 255, 255));
		jMenu1.setText("\u6211");

		jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
		jMenuItem1.setText("\u767b\u9646");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuItem2.setBackground(new java.awt.Color(255, 255, 255));
		jMenuItem2.setText("\u6ce8\u518c");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuItem5.setText("\u4e2a\u4eba\u4fe1\u606f");
		jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem5ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem5);

		jMenuItem3.setText("\u6536\u85cf");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jMenuItem3ActionPerformed(evt);
				} catch (UnknownHostException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		jMenu1.add(jMenuItem3);

		jMenuItem4.setText("\u8ba2\u5355");
		jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jMenuItem4ActionPerformed(evt);
				} catch (UnknownHostException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		jMenu1.add(jMenuItem4);

		jMenuItem6.setText("\u9000\u51fa\u8d26\u53f7");
		jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem6ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem6);

		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/*退出账号*/
	private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new HomeView().setVisible(true);
		this.dispose();
	}

	/*个人信息*/
	private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new CustomerInformation(customer).setVisible(true);
	}

	/*订单*/
	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) throws UnknownHostException, IOException, ClassNotFoundException {
		// TODO add your handling code here:
		new MyOrder(customer).setVisible(true);
	}

	/*收藏*/
	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) throws UnknownHostException, IOException, ClassNotFoundException {
		// TODO add your handling code here:
		new MYCollection(customer).setVisible(true);
	}

	/*更多*/
	private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		this.isLogined(isLogin);
		
		if(isLogin) {
			try {
				new ShopView("102", customer).setVisible(true);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	/*饮品*/
	private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		this.isLogined(isLogin);
		
		if(isLogin) {
			try {
				new ShopView("102", customer).setVisible(true);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	/*快餐*/
	private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		this.isLogined(isLogin);
		
		if(isLogin) {
			try {
				new ShopView("102", customer).setVisible(true);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	/*午餐*/
	private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		this.isLogined(isLogin);
		
		if(isLogin) {
			try {
				new ShopView("102", customer).setVisible(true);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	/*美食*/
	private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		this.isLogined(isLogin);
		
		if(isLogin) {
			try {
				new ShopView("102", customer).setVisible(true);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	/*点击地址时弹出个人信息界面*/
	private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		
	}

	/*搜索外卖*/
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
			throws UnknownHostException, IOException, ClassNotFoundException,
			SQLException {
		// TODO add your handling code here:
		String search = jTextField1.getText();
		new searchResult(search, customer).setVisible(true);
	}

	/*注册*/
	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new RegisterView().setVisible(true);
		this.dispose();
	}

	/*登陆*/

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new LoginView().setVisible(true);
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		try {
			org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
		} catch (Exception e) {
			//TODO exception
		}

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new HomeView().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JRadioButton jRadioButton4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTextField1;

	// End of variables declaration//GEN-END:variables

	/**
	 * 处理主页美化
	 * */

	public void drawHome() throws UnknownHostException, IOException,
			ClassNotFoundException, SQLException {

		jPanel3.setBackground(new Color(95, 142, 230)); //设置就jPanel3的背景颜色
		jButton1.setBackground(new Color(95, 142, 230)); //设置jButton1的背景颜色

		jLabel15.setIcon(new ImageIcon("Image/LOGO.png"));
		jLabel15.setText("");

		/*设置中部标签图片*/
		ImageIcon logoImgs[] = { new ImageIcon("Image/美食.png"),
				new ImageIcon("Image/午餐.png"), new ImageIcon("Image/快餐.png"),
				new ImageIcon("Image/饮品.png"), new ImageIcon("Image/更多.png") };

		JLabel logoLables[] = { jLabel2, jLabel3, jLabel4, jLabel5, jLabel6 };

		for (int i = 0; i < logoLables.length; i++) {
			logoLables[i].setIcon(logoImgs[i]);
		}

		jPanel2.setBackground(Color.WHITE); //设置jPanel2的背景颜色
		jPanel4.setBackground(Color.WHITE); //设置jPanel4的背景颜色

		/*轮播*/
		this.playTest();
		
		/*logo*/
		ImageIcon imgIcon = new ImageIcon("Image/Logo1.png");
		Image img = imgIcon.getImage();
		this.setIconImage(img);

	}

	/**
	 * 轮播
	 * */

	ImageIcon imgs[] = { new ImageIcon("Image/广告1.png"),
			new ImageIcon("Image/广告2.png"), new ImageIcon("Image/广告3.png"),
			new ImageIcon("Image/广告4.png") };

	private JRadioButton[] jrbs;
	private Thread t1;

	public void playTest() {

		jrbs = new JRadioButton[] { jRadioButton1, jRadioButton2,
				jRadioButton3, jRadioButton4 };

		t1 = new Thread(new Play(jLabel7, imgs, jrbs));
		t1.start();
	}

	/**
	 * 显示所有商家
	 * */

	ArrayList<Shop> shops;
	ArrayList<JPanel> jPanels = new ArrayList<JPanel>();

	Color color;

	public void getAllBusiness() throws UnknownHostException, IOException,
			ClassNotFoundException, SQLException {

		Client client = new Client();
		shops = client.showShop();

		System.out.println("size:" + shops.size());

		ArrayList<JLabel> imgLabels = new ArrayList<JLabel>();
		ArrayList<JLabel> nameLabels = new ArrayList<JLabel>();
		ArrayList<JLabel> scoreLabels = new ArrayList<JLabel>();
		ArrayList<JLabel> introLabels = new ArrayList<JLabel>();
		ArrayList<JLabel> feeLabels = new ArrayList<JLabel>();
		ArrayList<JLabel> typeLabels = new ArrayList<JLabel>();
		ArrayList<JLabel> averageLabels = new ArrayList<JLabel>();

		for (int i = 0; i < shops.size(); i++) {

			/*创建面板存储商家*/
			jPanels.add(new JPanel());
			jPanels.get(i).setSize(jPanel2.getWidth(), 150);
			jPanels.get(i).setBounds(
					0,
					100 + jPanel3.getHeight() + jPanel4.getHeight()
							+ jPanels.get(i).getHeight() * i,
					jPanel2.getWidth(), 150);
			jPanels.get(i).setBorder(
					BorderFactory.createMatteBorder(0, 0, 1, 0,
							Color.LIGHT_GRAY));
			jPanels.get(i).setBackground(Color.WHITE); //设置面板背景颜色
			jPanels.get(i).addMouseListener(this);

			jPanel2.add(jPanels.get(i));

			//获取背景颜色
			color = jPanels.get(i).getBackground();

			/*设置jPanel2面板最大值*/
			Dimension ds = new Dimension(jPanel2.getWidth(), jPanel3
					.getHeight()
					+ jPanel4.getHeight()
					+ jPanels.get(i).getHeight()
					* i
					+ 300);
			jPanel2.setPreferredSize(ds);

			/*设置jPanels.get(i)的布局*/
			jPanels.get(i).setLayout(null);

			/*显示商家*/

			/*添加商家头像*/

			imgLabels.add(new JLabel(new ImageIcon(ModelFactory.viewAllShop(
					customer).get(i).getSimage())));

			imgLabels.get(i).setBounds(20, 30, 80, 80);
			imgLabels.get(i).setBorder(BorderFactory.createEtchedBorder());
			jPanels.get(i).add(imgLabels.get(i));

			/*添加商家名*/
			nameLabels.add(new JLabel(ModelFactory.viewAllShop(customer).get(i)
					.getSname()));

			nameLabels.get(i).setBounds(120, 20, 200, 20);
			nameLabels.get(i).setFont(new Font("宋体", Font.BOLD, 14));
			jPanels.get(i).add(nameLabels.get(i));

			/*添加商家评估和月售量*/
			String score = "★";

			/*计算商店评分结果*/
			for (int j = 1; j < ModelFactory.viewAllShop(customer).get(i)
					.getScore(); j++) {
				score += "★";
			}

			scoreLabels.add(new JLabel(score));
			scoreLabels.get(i).setBounds(120, 60, 80, 20);
			scoreLabels.get(i).setForeground(Color.YELLOW);
			jPanels.get(i).add(scoreLabels.get(i));

			/*商家业绩*/
			introLabels
					.add(new JLabel(ModelFactory.viewAllShop(customer).get(i)
							.getScore()
							+ "  月售   "
							+ ModelFactory.viewAllShop(customer).get(i)
									.getCellCount()));

			introLabels.get(i).setBounds(200, 60, 200, 20);
			jPanels.get(i).add(introLabels.get(i));

			/*起送费*/
			feeLabels.add(new JLabel("起送   ￥"
					+ ModelFactory.viewAllShop(customer).get(i).getLowest()
					+ " | 配送   ￥ "
					+ ModelFactory.viewAllShop(customer).get(i).getFare()));
			feeLabels.get(i).setBounds(120, 120, 200, 20);
			jPanels.get(i).add(feeLabels.get(i));

			/*商店类型*/
			typeLabels.add(new JLabel(ModelFactory.viewAllShop(customer).get(i)
					.getType()));
			typeLabels.get(i).setBounds(120, 90, 80, 20);
			jPanels.get(i).add(typeLabels.get(i));

			/*人均消费*/
			averageLabels.add(new JLabel("人均   ￥"
					+ ModelFactory.viewAllShop(customer).get(i).getAverage()));
			averageLabels.get(i).setBounds(700, 90, 100, 50);
			jPanels.get(i).add(averageLabels.get(i));

		}

	}

	/**
	 * 点击对应商家
	 * */

	@Override
	public void mouseClicked(MouseEvent e) {
		// TODO Auto-generated method stub
		for (int i = 0; i < shops.size(); i++) {
			Shop shop=(Shop)shops.get(i);
			if (e.getSource().equals(jPanels.get(i))) {
				
				
				System.out.println(shop);
				try {
					//new ShopView(shop.getSid()).setVisible(true);
					System.out.println(shops.get(i).getSid());
					new ShopView(shops.get(i).getSid(), customer).setVisible(true);
					
				} catch (UnknownHostException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (ClassNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		}
	}

	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub
		for (int i = 0; i < shops.size(); i++) {
			if (e.getSource().equals(jPanels.get(i))) {
				jPanels.get(i).setBackground(new Color(173, 175, 173, 80));

			}
		}
	}

	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub
		for (int i = 0; i < shops.size(); i++) {
			if (e.getSource().equals(jPanels.get(i))) {

				jPanels.get(i).setBackground(color);

			}

		}
	}

	@Override
	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	public void setsearch() {
		jTextField1.addKeyListener(new KeyListener() {

			@Override
			public void keyTyped(KeyEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void keyReleased(KeyEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void keyPressed(KeyEvent e) {
				// TODO Auto-generated method stub
				String search = jTextField1.getText();
				try {
					new searchResult(search, customer).setVisible(true);
				} catch (UnknownHostException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (ClassNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
	}
	
	
}