package server;

/**
 * 
 * @author Administrator
 * Protocal: CUSTOMER_LOGIN, CUSTOMER_SIGNOUT, CUSTOMER_REGISTER,
 * 			 BUSNESS_LOGIN, BUSNESS_SINGOUT, BUNESS_REGISTER,
 * 			 COURIER_LOGIN, COURIER_SIGNOUT, COURIER_REGISTER,
 * 			 ADMINISTRATOR_LOGIN,ADMINISTRATOR_SIGNOUT
 */

public interface Protocal {
	
	int CUSTOMER_LOGIN = 101;
	int CUSTOMER_SIGNOUT = 1001;
	int CUSTOMER_REGISTER = 10001;
	int CUSTOMER_REMINDER = 20001;		//顾客催单
	int CUSTOMER_FAVORITE = 2002;		//顾客收藏
	int CUSTOMER_COLLECTION = 2003;     //顾客添加收藏
	int CUSTOMER_DELETECOLLECTION = 2004;   //顾客删除收藏
	int CUSTOMER_SEARCH=10004;
	int CUSTOMER_BUY=10005;    //用户购买
	int CUSTOMER_EDITINFORMATION=100003;//顾客修改个人信息
	int CUSTOMER_VIEWORDER=100011;     //用户查看订单
	int CUSTOMER_EVOLUATE=100012;     //用户评价
	int CUSTOMER_BUYFOOD=10012;    //顾客购买食物
	int CUSTOMER_VIEWREDEVENLOPE = 10013;		//商家查看店下红包
	int CUSTOMER_ADDREDEVENLOPE = 10014;		//商家添加红包
	int CUSTOMER_DELETEREDEVENLOPE = 10015;		//商家删除红包
	int CUSTOMER_USEREDEVENLOPE = 10016;		//用户使用红包
	int CUSTOMER_COMMENT = 10017;		//用户评论
	
	int BUSINESS_LOGIN = 102;
	int BUSINESS_SINGOUT = 1002;
	int BUSINESS_REGISTER = 10002;
	int BUSINESS_UPFOOD = 20002;		//上架商品
	int BUSINESS_DOWNFOOD = 20003;		//下架商品
	int BUSINESS_OPEN = 20004;			//开店
	int BUSINESS_CLOSE = 20005;			//关店
	int BUSINESS_VIEWCOMMENT = 20006;		//查看评论
	int BUSINESS_REPLAYCOMMENT = 20007;		//回复评论
	int BUSINESS_MODIFYINFORMATION = 20008;		//商家修改个人信息
	int BUSINESS_VIEWORDER = 20009;			//商家查看用户订单
	int BUSINESS_SHOWFOODS = 20010;       //商家管理自家的食物 
	int BUSINESS_GETSHOP = 20011;       //商家登陆成功后，获取自家商店的信息
	int BUSINESS_VIEWREDEVENLOPE = 20012;		//商家查看店下红包
	int BUSINESS_ADDREDEVENLOPE = 20013;		//商家添加红包
	int BUSINESS_DELETEREDEVENLOPE = 20014;		//商家删除红包
	int BUSINESS_STATUS = 20015;			//判断商家是否营业
	
	int COURIER_LOGIN = 103;
	int COURIER_SIGNOUT = 1003;
	int COURIER_REGISTER = 10003;
	int ADMINISTRATOR_LOGIN = 104;
	int ADMINISTRATOR_SIGNOUT = 1004;
	
	int SHOWALLSHOP=10086;    //主页展示所有商店
	
	int CUSTOMER_CONNECTBUSINESS = 10087;		//用户联系商家
	int CUSTOMER_READMESSAGE = 10088;			//用户读取信息
	int BUSINESS_CONNECTCUSTOMER = 10089;		//商家联系用户
	int BUSINESS_READMESSAGE = 10090;			//商家读取信息
}
