/*
 * searchResult.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;

import server.Client;

import model.Customer;
import model.Food;
import model.ModelFactory;
import model.Order;
import model.Shop;

/**
 *
 * @author  __USER__
 */
public class searchResult extends javax.swing.JFrame {
	Customer Cu = null;
	String search;
	/** Creates new form searchResult 
	 * @throws SQLException 
	 * @throws ClassNotFoundException 
	 * @throws IOException 
	 * @throws UnknownHostException */
	public searchResult(String search, Customer Cu)
			throws UnknownHostException, IOException, ClassNotFoundException,
			SQLException {
		this.Cu = Cu;
		this.search = search;
		initComponents();
		jScrollPane1
				.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
		searchResults(search);
		drawOrder();
		this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
		this.setResizable(false);
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel2 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("\u67e5\u627e\u7ed3\u679c:");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout.createSequentialGroup().addGap(172, 172, 172)
						.addComponent(jLabel1).addContainerGap(208,
								Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1).addContainerGap(
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 456,
				Short.MAX_VALUE));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 445,
				Short.MAX_VALUE));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout.createSequentialGroup().addGroup(
						jPanel2Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								false).addComponent(jPanel4,
								javax.swing.GroupLayout.Alignment.LEADING,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addComponent(jPanel3,
								javax.swing.GroupLayout.Alignment.LEADING,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)).addContainerGap(41,
						Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel4,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addContainerGap()));

		jScrollPane1.setViewportView(jPanel2);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524,
				Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/*
	 * 索索结果
	 */
	ArrayList<Food> foods;
	ArrayList<JPanel> jPanels;
	ArrayList<JLabel> shopNameLabels;
	ArrayList<JPanel> foodPanels;
	ArrayList<JLabel> imageLabels;
	ArrayList<JLabel> nameLabels;
	ArrayList<JLabel> informationLabels;
	ArrayList<JLabel> priceLabels;
	ArrayList<JSpinner> buyCounts;
	ArrayList<JButton> collectionButtons = new ArrayList<JButton>();
	ArrayList<JButton> buyButtons = new ArrayList<JButton>();

	public void searchResults(String search) throws UnknownHostException,
			IOException, ClassNotFoundException, SQLException {
		Client client = new Client();
		foods = client.searchResult(search);

		jPanels = new ArrayList<JPanel>();
		shopNameLabels = new ArrayList<JLabel>();
		foodPanels = new ArrayList<JPanel>();
		imageLabels = new ArrayList<JLabel>();
		nameLabels = new ArrayList<JLabel>();
		informationLabels = new ArrayList<JLabel>();
		priceLabels = new ArrayList<JLabel>();
		buyCounts = new ArrayList<JSpinner>();
		jPanel4.setLayout(null);
		System.out.println(foods.size());
		for (int i = 0; i < foods.size(); i++) {
			/*先创建一个面板*/
			jPanels.add(new JPanel());
			jPanels.get(i).setSize(jPanel4.getWidth(), 150);
			jPanels.get(i).setBounds(0, jPanels.get(i).getHeight() * i,
					jPanel4.getWidth(), 150);
			jPanels.get(i).setBorder(BorderFactory.createEtchedBorder());
			jPanels.get(i).add(new JLabel("" + i));
			jPanel4.add(jPanels.get(i));

			/*设置jPanel2面板最大值*/
			Dimension ds = new Dimension(jPanel4.getWidth(), jPanels.get(i)
					.getHeight()
					* i + 300);
			jPanel4.setPreferredSize(ds);
			/*添加商店名*/
			shopNameLabels.add(new JLabel("商店："
					+ ModelFactory.searchResult(search).get(i).getSname()));
			jPanels.get(i).setLayout(null);
			shopNameLabels.get(i).setBounds(20, 10, 140, 20);
			jPanels.get(i).add(shopNameLabels.get(i));

			/*添加显示搜索面板*/
			foodPanels.add(new JPanel());

			jPanels.get(i).setLayout(null);
			foodPanels.get(i).setBounds(20, 35, 400, 80);
			foodPanels.get(i).setBackground(Color.LIGHT_GRAY);
			jPanels.get(i).add(foodPanels.get(i));

			/*添加食物图片*/
			imageLabels.add(new JLabel(new ImageIcon("Image/"
					+ ModelFactory.searchResult(search).get(i).getImage())));

			foodPanels.get(i).setLayout(null);
			imageLabels.get(i).setBounds(10, 10, 60, 60);
			foodPanels.get(i).add(imageLabels.get(i));

			/*添加食物名字*/
			nameLabels.add(new JLabel(ModelFactory.searchResult(search).get(i)
					.getFoodName()));

			foodPanels.get(i).setLayout(null);
			nameLabels.get(i).setBounds(90, 10, 150, 20);
			foodPanels.get(i).add(nameLabels.get(i));

			/*添加食物描述*/
			informationLabels.add(new JLabel(ModelFactory.searchResult(search)
					.get(i).getFoodInformation()));

			foodPanels.get(i).setLayout(null);
			informationLabels.get(i).setBounds(90, 40, 150, 20);
			foodPanels.get(i).add(informationLabels.get(i));

			/*添加订单价钱*/
			priceLabels.add(new JLabel("￥ "
					+ ModelFactory.searchResult(search).get(i).getFoodPrice()));
			foodPanels.get(i).setLayout(null);
			priceLabels.get(i).setBounds(300, 60, 150, 20);
			foodPanels.get(i).add(priceLabels.get(i));

			/*添加收藏按钮*/
			collectionButtons.add(new JButton("收藏"));

			jPanels.get(i).setLayout(null);
			collectionButtons.get(i).setBounds(250, 120, 60, 20);
			/**
			 * 点击收藏执行事件
			 * */
			collectionButtons.get(i).addActionListener(new ActionListener() {
				
				@Override
				public void actionPerformed(ActionEvent e) {
					// TODO Auto-generated method stub
					for(int i=0;i<foods.size();i++){
						if(e.getSource().equals(collectionButtons.get(i))){
							try {
								Client client =new Client();
								client.addcollection(foods.get(i).getFoodName(), "Image/"+foods.get(i).getImage(), foods.get(i).getSname(), foods.get(i).getSid(), foods.get(i).getSname(), Cu.getCid());
								
							} catch (Exception e1) {
								// TODO Auto-generated catch block
								e1.printStackTrace();
							}
						}
					}
				}
			});
			jPanels.get(i).add(collectionButtons.get(i));

			/*添加购买按钮*/
			buyButtons.add(new JButton("购买"));

			jPanels.get(i).setLayout(null);
			buyButtons.get(i).setBounds(350, 120, 60, 20);
			
			/**
			 * 点击购买执行事件
			 */
			buyButtons.get(i).addActionListener(new ActionListener() {

				@Override
				public void actionPerformed(ActionEvent e) {
					// TODO Auto-generated method stub
						try {
							Client c = new Client();
							for(int i=0;i<foods.size();i++){
								if(e.getSource().equals(buyButtons.get(i))){
									//c.buyFood(foods.get(i).getFoodName(), foods.get(i).getImage(), foods.get(i).getFoodPrice()+"", Cu.getCid(), foods.get(i).getSid(), "2", 1, foods.get(i).getSname());
								}
							
							}
						} catch (Exception e1) {
							// TODO Auto-generated catch block
							e1.printStackTrace();
						}
						
				}
			});
			
			
			jPanels.get(i).add(buyButtons.get(i));
			
			
		}
	}

	/**
	 * @param args the command line arguments
	 */

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;

	// End of variables declaration//GEN-END:variables

	/**处理页面美化**/

	public void drawOrder() {
		jPanel3.setBackground(new Color(95, 142, 230)); //设置jPanel1背景颜色

	}

}